//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkThirdLevel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int IdUser { get; set; }
        public int IdDocument { get; set; }
        public Nullable<bool> tech { get; set; }
        public int IdFav { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual User User { get; set; }
    }
}
